sudo: required
services: 
  - docker

before_install:
  - docker build -t pramod2804/docker-smaple -f Dockerfile.dev .

script:
  - docker run -e CI=true pramod2804/docker-smaple npm rum test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-542605267262"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  